import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import './Landing.css'

const HEADLINE_FULL = 'Raw Catalog.\nClean Record.'

const BOOT_LINES = [
  { type: 'prompt',  text: '$ specforge --process "LM741CN, Texas Instruments, Op-Amp General"', delay: 200 },
  { type: 'spacer',  text: '', delay: 450 },
  { type: 'heading', text: '[ CLEAN ] Stripping placeholder values...', delay: 500 },
  { type: 'warn',    text: '⚠ Brand field: "-- No Unilog Brand --" → flagged blank', delay: 750 },
  { type: 'success', text: '✓ Clean complete', delay: 1000 },
  { type: 'spacer',  text: '', delay: 1100 },
  { type: 'heading', text: '[ RESOLVE BRAND ] Fuzzy-matching canonical form...', delay: 1150 },
  { type: 'output',  text: '  Input: "Texas Instruments Inc."', delay: 1400 },
  { type: 'output',  text: '  Candidate: "Texas Instruments" — score: 0.96', delay: 1650 },
  { type: 'success', text: '✓ Canonical: "Texas Instruments" (Unicat #48291)', delay: 1900 },
  { type: 'spacer',  text: '', delay: 2050 },
  { type: 'heading', text: '[ CLASSIFY ] Resolving UNSPSC classpath...', delay: 2100 },
  { type: 'output',  text: '  Electronics › ICs › Op-Amps › General Purpose', delay: 2350 },
  { type: 'success', text: '✓ 32131601 — 14 expected attributes loaded', delay: 2600 },
  { type: 'spacer',  text: '', delay: 2750 },
  { type: 'heading', text: '[ EXTRACT ] Pulling attributes from sources...', delay: 2800 },
  { type: 'output',  text: '  Supply Voltage, Bandwidth, Slew Rate, Package...', delay: 3050 },
  { type: 'success', text: '✓ 11/14 extracted  3 known-missing', delay: 3300 },
  { type: 'spacer',  text: '', delay: 3450 },
  { type: 'heading', text: '[ NORMALIZE ] Constraining to approved vocabulary...', delay: 3500 },
  { type: 'output',  text: '  "inches" → "IN."  "DIP8" → "DIP-8"  "±18v" → "±18V"', delay: 3750 },
  { type: 'success', text: '✓ 11 values mapped to controlled vocabulary', delay: 4000 },
  { type: 'spacer',  text: '', delay: 4150 },
  { type: 'heading', text: '[ VERIFY ] Cross-referencing source entailment...', delay: 4200 },
  { type: 'warn',    text: '⚠ Supply Voltage: SRC-A=±18V (datasheet)  SRC-B=±22V (distributor)', delay: 4500 },
  { type: 'spacer',  text: '', delay: 4700 },
  { type: 'heading', text: '[ ADJUDICATE ] Resolving conflict...', delay: 4750 },
  { type: 'output',  text: '  P1 Manufacturer Datasheet beats P3 Distributor', delay: 5000 },
  { type: 'success', text: '✓ ±18V — reasoning logged', delay: 5250 },
  { type: 'spacer',  text: '', delay: 5400 },
  { type: 'heading', text: '[ BUILD DESCRIPTION ] Generating variants...', delay: 5450 },
  { type: 'success', text: '✓ Mobile / Short / Long / Invoice / Retail written', delay: 5700 },
  { type: 'spacer',  text: '', delay: 5850 },
  { type: 'heading', text: '[ AUDIT ] Coverage + confidence + readiness...', delay: 5900 },
  { type: 'warn',    text: '⚠ Readiness: NEEDS REVIEW — 9/14 fully resolved', delay: 6150 },
  { type: 'spacer',  text: '', delay: 6300 },
  { type: 'heading', text: '[ MAP OUTPUT ] Writing to Delivery Format columns...', delay: 6350 },
  { type: 'success', text: '✓ Record WO-20240811-001 complete', delay: 6600 },
  { type: 'success', text: '✓ 3 fields → review queue', delay: 6800 },
]

const PIPELINE_STAGES = [
  { num: '01', name: 'Clean',               desc: 'Strip & flag placeholder values' },
  { num: '02', name: 'Resolve Brand',        desc: 'Fuzzy-match to canonical Unicat form' },
  { num: '03', name: 'Classify',             desc: 'UNSPSC classpath + attribute schema' },
  { num: '04', name: 'Extract',              desc: 'Multi-source field extraction' },
  { num: '05', name: 'Normalize',            desc: 'Constrain to approved LOV / UOM' },
  { num: '06', name: 'Verify',               desc: 'Source grounding & entailment check' },
  { num: '07', name: 'Adjudicate',           desc: 'Conflict resolution with logged reasoning' },
  { num: '08', name: 'Build Description',    desc: 'Formula-driven description variants' },
  { num: '09', name: 'Audit',                desc: 'Coverage, confidence, review flags' },
  { num: '10', name: 'Map Output',           desc: 'Delivery Format column mapping' },
]

const CAPABILITIES = [
  {
    num: '01',
    title: 'Brand Resolution',
    desc: 'Fuzzy-match messy manufacturer and brand strings to their one canonical approved form in the Unicat list. Logged confidence and fallback note on every record.',
  },
  {
    num: '02',
    title: 'Vocabulary Control',
    desc: 'Every extracted value is forced into its LOV-approved form. Nothing outside the controlled vocabulary is passed through — it is mapped, or flagged.',
  },
  {
    num: '03',
    title: 'Description Variants',
    desc: 'Mobile, Invoice, Short, Long, Retail, Marketing, and Features 1–20 generated by formula from verified fields. Character-limit compliance checked on every variant.',
  },
  {
    num: '04',
    title: 'Conflict Adjudication',
    desc: 'Source priority applied top-down (Manufacturer Datasheet → Website → Distributor → Other). Conflict resolution is logged per field — fully traceable.',
  },
  {
    num: '05',
    title: 'Audit & Coverage',
    desc: 'Per-field confidence, entailment label, missing-field markers, and a readiness state (Ready / Needs Review / Incomplete) on every processed record.',
  },
]

export default function Landing() {
  const navigate = useNavigate()
  const [headline, setHeadline] = useState('')
  const [headlineDone, setHeadlineDone] = useState(false)
  const [visibleLines, setVisibleLines] = useState([])
  const termRef = useRef(null)
  const timeoutsRef = useRef([])

  // Typewriter headline
  useEffect(() => {
    let i = 0
    const tick = () => {
      if (i <= HEADLINE_FULL.length) {
        setHeadline(HEADLINE_FULL.slice(0, i))
        i++
        const t = setTimeout(tick, i === 1 ? 400 : 45)
        timeoutsRef.current.push(t)
      } else {
        setHeadlineDone(true)
      }
    }
    const t = setTimeout(tick, 300)
    timeoutsRef.current.push(t)
    return () => timeoutsRef.current.forEach(clearTimeout)
  }, [])

  // Terminal boot sequence
  useEffect(() => {
    BOOT_LINES.forEach((line, idx) => {
      const t = setTimeout(() => {
        setVisibleLines(prev => [...prev, idx])
        if (termRef.current) {
          termRef.current.scrollTop = termRef.current.scrollHeight
        }
      }, line.delay)
      timeoutsRef.current.push(t)
    })
    return () => timeoutsRef.current.forEach(clearTimeout)
  }, [])

  // Format headline with line break
  const headlineLines = headline.split('\n')

  return (
    <div className="landing">
      {/* Top bar */}
      <header className="land-topbar">
        <div className="land-topbar-logo">SpecForge</div>
        <nav className="land-topbar-nav">
          <span className="land-topbar-link" onClick={() => navigate('/input')}>New Record</span>
          <span className="land-topbar-link" onClick={() => navigate('/batch')}>Batch</span>
          <span className="land-topbar-link" onClick={() => navigate('/history')}>Library</span>
          <span className="land-topbar-link" onClick={() => navigate('/settings')}>Settings</span>
        </nav>
      </header>

      {/* Hero */}
      <section className="land-hero">
        {/* Left */}
        <div className="land-hero-left">
          <div>
            <p className="land-hero-eyebrow">[ Product Intelligence Platform ]</p>
            <h1 className="land-hero-headline text-heading">
              {headlineLines.map((line, i) => (
                <span key={i}>
                  {line}
                  {i < headlineLines.length - 1 && <br />}
                </span>
              ))}
              {!headlineDone && <span className="typewriter-cursor" />}
            </h1>
            <p className="land-hero-sub">
              SpecForge turns messy distributor catalog rows — manufacturer part numbers, short descriptions, unresolved brand strings, placeholder values — into structured, vocabulary-controlled product records for industrial commerce.
            </p>
            <div className="land-hero-cta-row">
              <button className="btn btn-primary" onClick={() => navigate('/input')}>
                New Work Order
              </button>
              <button className="btn" onClick={() => navigate('/batch')}>
                Batch Upload
              </button>
            </div>
          </div>

          <div className="land-hero-meta">
            <div className="land-hero-meta-grid">
              <div className="land-hero-meta-cell">
                <span className="land-hero-meta-value">10</span>
                <span className="land-hero-meta-label">Pipeline stages</span>
              </div>
              <div className="land-hero-meta-cell">
                <span className="land-hero-meta-value">LOV</span>
                <span className="land-hero-meta-label">Vocab-controlled</span>
              </div>
              <div className="land-hero-meta-cell">
                <span className="land-hero-meta-value">&lt;10s</span>
                <span className="land-hero-meta-label">Per record</span>
              </div>
            </div>
          </div>
        </div>

        {/* Right — terminal */}
        <div className="land-hero-right">
          <div className="land-terminal-header">
            <div className="land-terminal-dot" />
            <span className="land-terminal-title">specforge-engine v2.0 — Live Processing</span>
          </div>
          <div className="land-terminal-body" ref={termRef}>
            {BOOT_LINES.map((line, idx) =>
              visibleLines.includes(idx) ? (
                <div key={idx} className={`land-term-line ${line.type}`}>
                  {line.text}
                </div>
              ) : null
            )}
          </div>
        </div>
      </section>

      {/* What it fixes — the problem framing */}
      <section className="land-problem">
        <div className="land-problem-inner">
          <div className="land-problem-label">// The Problem</div>
          <div className="land-problem-grid">
            <div className="land-problem-before">
              <div className="land-problem-side-label">Raw Distributor Row</div>
              <div className="land-problem-row">
                <span className="land-problem-field">MPN</span>
                <span className="land-problem-val raw">LM741CN/NOPB</span>
              </div>
              <div className="land-problem-row">
                <span className="land-problem-field">Brand</span>
                <span className="land-problem-val placeholder">-- No Unilog Brand --</span>
              </div>
              <div className="land-problem-row">
                <span className="land-problem-field">Manufacturer</span>
                <span className="land-problem-val raw">Texas Instruments Inc.</span>
              </div>
              <div className="land-problem-row">
                <span className="land-problem-field">Description</span>
                <span className="land-problem-val raw">OP AMP, SGL, 1MHZ, 0.5V/US, DIP-8 ±18V</span>
              </div>
              <div className="land-problem-row">
                <span className="land-problem-field">UOM</span>
                <span className="land-problem-val raw">each</span>
              </div>
            </div>
            <div className="land-problem-arrow">→</div>
            <div className="land-problem-after">
              <div className="land-problem-side-label">SpecForge Record</div>
              <div className="land-problem-row">
                <span className="land-problem-field">MPN</span>
                <span className="land-problem-val clean">LM741CN/NOPB</span>
              </div>
              <div className="land-problem-row">
                <span className="land-problem-field">Brand</span>
                <span className="land-problem-val clean">Texas Instruments <span className="land-problem-match">[ #48291 ✓ ]</span></span>
              </div>
              <div className="land-problem-row">
                <span className="land-problem-field">Manufacturer</span>
                <span className="land-problem-val clean">Texas Instruments</span>
              </div>
              <div className="land-problem-row">
                <span className="land-problem-field">Classpath</span>
                <span className="land-problem-val clean">32131601 — Op-Amps, General Purpose</span>
              </div>
              <div className="land-problem-row">
                <span className="land-problem-field">UOM</span>
                <span className="land-problem-val clean">EA <span className="land-problem-match">[ LOV ✓ ]</span></span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Capabilities */}
      <section className="land-features">
        {CAPABILITIES.map(f => (
          <div className="land-feature-cell" key={f.num}>
            <span className="land-feature-number">[ {f.num} ]</span>
            <div className="land-feature-title">{f.title}</div>
            <div className="land-feature-desc">{f.desc}</div>
          </div>
        ))}
      </section>

      {/* Pipeline diagram */}
      <section className="land-pipeline">
        <div className="land-pipeline-label">// 10-Stage Pipeline</div>
        <div className="land-pipeline-stages">
          {PIPELINE_STAGES.map((s, i) => (
            <div className="land-pipeline-stage" key={s.num}>
              <span className="land-pipeline-stage-num">{s.num}</span>
              <div className="land-pipeline-stage-name">[ {s.name} ]</div>
              <div className="land-pipeline-stage-desc">{s.desc}</div>
              {i < PIPELINE_STAGES.length - 1 && (
                <div className="land-pipeline-connector">›</div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="land-footer">
        <span className="land-footer-copy">
          SpecForge — REV 2.0 — Product Intelligence Platform
        </span>
        <div className="land-footer-links">
          <span className="land-footer-link" onClick={() => navigate('/settings')}>Settings</span>
          <span className="land-footer-link" onClick={() => navigate('/history')}>Library</span>
          <span className="land-footer-link" onClick={() => navigate('/batch')}>Batch</span>
          <span className="land-footer-link" onClick={() => navigate('/input')}>New Record</span>
        </div>
      </footer>
    </div>
  )
}
